# Generated by Django 3.0 on 2019-12-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_producttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='product-thumnails'),
        ),
    ]
