# Generated by Django 3.0 on 2019-12-03 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productimages_thumbnail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
